/* ============================================================
   易經 · EL ORÁCULO DE LAS MUTACIONES
   ------------------------------------------------------------
   Datos verificados: los 8 trigramas del Bagua, los 64
   hexagramas en secuencia King Wen (con sus caracteres Unicode
   reales del bloque U+4DC0–U+4DFF, que sigue exactamente el
   orden King Wen), y los Acertijos del Sabio para el minijuego.
   Todo el texto interpretativo es redacción original.
   ============================================================ */

const TRIGRAMAS = {
  qian: { simbolo: "☰", hanzi: "乾", pinyin: "Qián", nombre: "Cielo",   binario: "111" },
  kun:  { simbolo: "☷", hanzi: "坤", pinyin: "Kūn",  nombre: "Tierra",  binario: "000" },
  zhen: { simbolo: "☳", hanzi: "震", pinyin: "Zhèn", nombre: "Trueno",  binario: "100" },
  kan:  { simbolo: "☵", hanzi: "坎", pinyin: "Kǎn",  nombre: "Agua",    binario: "010" },
  gen:  { simbolo: "☶", hanzi: "艮", pinyin: "Gèn",  nombre: "Montaña", binario: "001" },
  xun:  { simbolo: "☴", hanzi: "巽", pinyin: "Xùn",  nombre: "Viento",  binario: "011" },
  li:   { simbolo: "☲", hanzi: "離", pinyin: "Lí",   nombre: "Fuego",   binario: "101" },
  dui:  { simbolo: "☱", hanzi: "兌", pinyin: "Duì",  nombre: "Lago",    binario: "110" },
};

const HEXAGRAMAS = [
{num:1,unicode:"䷀",hanzi:"乾",pinyin:"Qián",nombre:"Lo Creativo",subtitulo:"El Cielo",trigInf:"qian",trigSup:"qian",
 esencia:"La fuerza creadora sin descanso",
 narracion:"Seis trazos íntegros se elevan como el cielo mismo: pura energía en movimiento perpetuo. Es el impulso original del que nace todo lo demás.",
 dictamen:"Un momento de gran fuerza creadora favorece la acción decidida. El éxito llega a quien persevera con firmeza, siempre que la fortaleza no se vuelva dureza ni el impulso se vuelva soberbia.",
 imagen:"El cielo se mueve con vigor incesante. Así también la persona noble se fortalece a sí misma sin pausa, cultivando su carácter con la misma constancia con que los astros recorren su órbita."},
{num:2,unicode:"䷁",hanzi:"坤",pinyin:"Kūn",nombre:"Lo Receptivo",subtitulo:"La Tierra",trigInf:"kun",trigSup:"kun",
 esencia:"Entrega fértil, la fuerza de sostener",
 narracion:"Seis trazos quebrados dibujan la llanura infinita: no impone, recibe. Su fuerza está en la entrega, no en el mando; en dar cabida a lo que el cielo siembra.",
 dictamen:"Este es tiempo de ceder el protagonismo y sostener en vez de imponer. Quien avanza como guía y no como jefe encuentra buena fortuna; la iniciativa impulsiva, en cambio, se pierde en el camino.",
 imagen:"La tierra en su naturaleza es entrega abundante. Así la persona noble, de virtud generosa, sostiene y da cabida a todo lo que la rodea."},
{num:3,unicode:"䷂",hanzi:"屯",pinyin:"Zhūn",nombre:"La Dificultad Inicial",subtitulo:"El Brote",trigInf:"zhen",trigSup:"kan",
 esencia:"El caos fértil de todo comienzo",
 narracion:"Un trueno se agita bajo aguas profundas: la energía quiere nacer pero el camino aún no está trazado. Es el brote que empuja la tierra dura, la dificultad propia de lo que recién comienza.",
 dictamen:"Los inicios rara vez son claros. Conviene no forzar el avance en soledad, sino buscar ayudantes y trazar cimientos firmes antes de dar el gran paso; la perseverancia paciente trae fruto.",
 imagen:"Nubes y trueno: así es la dificultad inicial. La persona noble, en tiempos confusos, ordena y organiza antes de actuar."},
{num:4,unicode:"䷃",hanzi:"蒙",pinyin:"Méng",nombre:"La Necedad Juvenil",subtitulo:"El Aprendizaje",trigInf:"kan",trigSup:"gen",
 esencia:"La mente inexperta que busca guía",
 narracion:"Al pie de la montaña brota un manantial que aún no sabe hacia dónde correr: es la mente joven, llena de preguntas, necesitada de cauce y de maestro.",
 dictamen:"No es el maestro quien busca al discípulo distraído, sino el discípulo sincero quien busca al maestro. Preguntar una vez con humildad trae claridad; insistir con necedad solo cansa la respuesta.",
 imagen:"Bajo la montaña brota el manantial: así nace la necedad juvenil. La persona noble forma su carácter con acción decidida y nutre su virtud desde el origen."},
{num:5,unicode:"䷄",hanzi:"需",pinyin:"Xū",nombre:"La Espera",subtitulo:"El Sustento",trigInf:"qian",trigSup:"kan",
 esencia:"La calma activa antes del cruce",
 narracion:"El cielo poderoso se detiene frente a las aguas peligrosas: no retrocede, espera. Reúne fuerzas, se nutre, confía en el momento justo para avanzar.",
 dictamen:"La espera con el corazón sincero, sin ansiedad, atrae buena fortuna. Forzar el cruce del río antes de tiempo trae peligro; la paciencia activa —comer, descansar, prepararse— es la verdadera acción de este momento.",
 imagen:"Nubes suben al cielo: así es la espera. La persona noble come, bebe y se alegra mientras aguarda su hora."},
{num:6,unicode:"䷅",hanzi:"訟",pinyin:"Sòng",nombre:"El Conflicto",subtitulo:"",trigInf:"kan",trigSup:"qian",
 esencia:"La tensión entre fuerzas que no ceden",
 narracion:"El agua desciende mientras el cielo asciende: dos voluntades que se alejan en direcciones opuestas. De ahí nace la disputa, el desacuerdo que no encuentra tierra común.",
 dictamen:"Aun con razón de sobra, llevar el conflicto hasta el final trae desgracia. Es mejor detenerse a mitad de camino y buscar a alguien justo que medie, que insistir en cruzar aguas profundas mientras dura la disputa.",
 imagen:"Cielo y agua se mueven en direcciones opuestas: así es el conflicto. La persona noble, al iniciar cualquier empresa, medita bien sus comienzos para no sembrar disputas futuras."},
{num:7,unicode:"䷆",hanzi:"師",pinyin:"Shī",nombre:"El Ejército",subtitulo:"La Conducción",trigInf:"kan",trigSup:"kun",
 esencia:"La disciplina colectiva bajo un mando justo",
 narracion:"Las aguas profundas descansan bajo la llanura: así se oculta la disciplina dentro de la aparente calma. Es la fuerza organizada de muchos guiados por uno solo.",
 dictamen:"Conducir a otros requiere experiencia y rectitud, no solo autoridad. Un mando sabio y disciplinado trae éxito sin reproche; el desorden en las filas, en cambio, siembra desgracia.",
 imagen:"En medio de la tierra hay agua: así es el ejército. La persona noble sostiene a su gente y acumula a las masas con generosidad."},
{num:8,unicode:"䷇",hanzi:"比",pinyin:"Bǐ",nombre:"La Unión",subtitulo:"El Acercamiento",trigInf:"kun",trigSup:"kan",
 esencia:"El vínculo que sostiene y protege",
 narracion:"El agua se derrama sobre la tierra y la empapa por completo: no hay grieta entre ambas. Es la imagen de la unión sincera, del acercamiento que nace de la confianza mutua.",
 dictamen:"Unirse trae buena fortuna, pero solo si la alianza nace de un centro genuino y no del cálculo. Quien tarda en sumarse pierde su lugar; conviene acercarse pronto y con el corazón dispuesto.",
 imagen:"Sobre la tierra hay agua: así es la unión. Los antiguos reyes, siguiendo este signo, fundaban ciudades y estrechaban lazos con los señores aliados."},
{num:9,unicode:"䷈",hanzi:"小畜",pinyin:"Xiǎo Xù",nombre:"La Fuerza Domesticadora de lo Pequeño",subtitulo:"",trigInf:"qian",trigSup:"xun",
 esencia:"La contención suave que frena lo grande",
 narracion:"El viento sopla sobre el cielo: fuerza gentil que no puede detener lo inmenso, solo demorarlo un poco. Son las nubes densas que aún no logran soltar la lluvia.",
 dictamen:"Los grandes proyectos deben esperar; solo lo pequeño y cercano se puede realizar hoy. Cultivar la virtud interior en la contención trae, con el tiempo, la fuerza suficiente para lo mayor.",
 imagen:"El viento recorre el cielo: así es la fuerza domesticadora de lo pequeño. La persona noble refina su virtud interior mientras aguarda el momento de mayor alcance."},
{num:10,unicode:"䷉",hanzi:"履",pinyin:"Lǚ",nombre:"El Proceder",subtitulo:"Pisar con Cuidado",trigInf:"dui",trigSup:"qian",
 esencia:"Avanzar con tacto entre fuerzas mayores",
 narracion:"Un lago sereno se extiende bajo el cielo inmenso: lo pequeño y gozoso camina justo detrás de lo grande y poderoso, pisando con cuidado, sin provocar.",
 dictamen:"Pisar la cola del tigre sin ser mordido: eso es proceder con tacto frente a fuerzas mayores. La cortesía sincera y sin servilismo permite avanzar entre peligros sin sufrir daño.",
 imagen:"Arriba el cielo, abajo el lago: así es el proceder correcto. La persona noble distingue lo alto de lo bajo y así afirma la voluntad del pueblo."},
{num:11,unicode:"䷊",hanzi:"泰",pinyin:"Tài",nombre:"La Paz",subtitulo:"",trigInf:"qian",trigSup:"kun",
 esencia:"El cielo y la tierra se encuentran en armonía",
 narracion:"La energía del cielo desciende, la de la tierra asciende: se cruzan y se abrazan. Es el signo más pleno de armonía, cuando lo alto y lo bajo dialogan sin jerarquía.",
 dictamen:"Lo pequeño se retira, lo grande se acerca: gran fortuna y éxito. Es momento de sembrar y construir, porque cielo y tierra colaboran; pero la paz lograda también pide cuidado para no volverse descuido.",
 imagen:"Cielo y tierra se unen: así es la paz. El gobernante, siguiendo este signo, ordena el curso natural de las cosas y ayuda a que cada parte encuentre su lugar."},
{num:12,unicode:"䷋",hanzi:"否",pinyin:"Pǐ",nombre:"El Estancamiento",subtitulo:"",trigInf:"kun",trigSup:"qian",
 esencia:"El diálogo cortado entre lo alto y lo bajo",
 narracion:"El cielo se aleja hacia arriba, la tierra se hunde hacia abajo: ya no se tocan. Es el signo opuesto a la paz, cuando las fuerzas se dan la espalda y nada fluye entre ellas.",
 dictamen:"No es momento favorable para la persona correcta; conviene retirarse, guardar la propia integridad y no mezclarse con lo que decae. La paciencia protege lo que aún puede salvarse.",
 imagen:"Cielo y tierra no se comunican: así es el estancamiento. La persona noble se repliega en su virtud para evitar el peligro y no busca honores mientras dure la desunión."},
{num:13,unicode:"䷌",hanzi:"同人",pinyin:"Tóng Rén",nombre:"La Comunidad de Hombres",subtitulo:"",trigInf:"li",trigSup:"qian",
 esencia:"El fuego que se une bajo el cielo abierto",
 narracion:"El fuego se eleva hacia el cielo, buscando su misma naturaleza luminosa: personas que se reconocen entre sí y forman comunidad más allá de intereses estrechos.",
 dictamen:"La verdadera comunidad no se funda en el clan ni en el interés privado, sino en un propósito amplio y compartido. Cruzar juntos las grandes aguas es posible cuando la unión es sincera.",
 imagen:"El cielo junto con el fuego: así es la comunidad de hombres. La persona noble distingue las cosas por sus categorías y así ordena a los seres sin perder de vista lo que los une."},
{num:14,unicode:"䷍",hanzi:"大有",pinyin:"Dà Yǒu",nombre:"La Gran Posesión",subtitulo:"",trigInf:"qian",trigSup:"li",
 esencia:"La abundancia que ilumina desde lo alto",
 narracion:"El fuego brilla en lo alto del cielo, iluminando todo lo que existe: es la abundancia sostenida por la claridad, la riqueza que no se guarda sino que se comparte con luz propia.",
 dictamen:"La gran posesión —de bienes, talento o influencia— trae éxito supremo cuando se administra con humildad y se pone al servicio del bien común, nunca cuando se acumula por vanidad.",
 imagen:"El fuego está en lo alto del cielo: así es la gran posesión. La persona noble contiene el mal y fomenta el bien, obedeciendo así la benévola voluntad del cielo."},
{num:15,unicode:"䷎",hanzi:"謙",pinyin:"Qiān",nombre:"La Modestia",subtitulo:"",trigInf:"gen",trigSup:"kun",
 esencia:"La montaña que se inclina bajo la llanura",
 narracion:"Una montaña, lo más alto, se oculta bajo la tierra llana: la verdadera grandeza no necesita mostrarse. Es la modestia genuina, que nivela sin borrar lo que vale.",
 dictamen:"La modestia sincera trae éxito en toda empresa. Quien tiene mérito y no lo exhibe completa lo que emprende; el destino mismo favorece a quien se inclina sin perder su fuerza interior.",
 imagen:"En medio de la tierra hay una montaña: así es la modestia. La persona noble reduce lo que sobra y aumenta lo que falta, dando a cada cosa su justa medida."},
{num:16,unicode:"䷏",hanzi:"豫",pinyin:"Yù",nombre:"El Entusiasmo",subtitulo:"",trigInf:"kun",trigSup:"zhen",
 esencia:"El trueno que despierta la tierra dormida",
 narracion:"El trueno resuena y sale de la tierra: es el entusiasmo que mueve a las masas, la energía compartida que nace cuando un propósito común enciende a todos a la vez.",
 dictamen:"El entusiasmo bien dirigido —hacia una causa clara, con colaboradores firmes— trae gran fortuna. Pero el entusiasmo sin rumbo se dispersa como el trueno que se aleja sin dejar lluvia.",
 imagen:"El trueno sale de la tierra con fuerza: así es el entusiasmo. Los antiguos reyes, siguiendo este signo, componían música para honrar la virtud."},
{num:17,unicode:"䷐",hanzi:"隨",pinyin:"Suí",nombre:"El Seguimiento",subtitulo:"",trigInf:"zhen",trigSup:"dui",
 esencia:"Adaptarse con gozo al ritmo del momento",
 narracion:"El trueno se esconde dentro del lago: la fuerza que se adapta, que sabe ceder el paso y seguir la corriente del momento sin perder su propio centro.",
 dictamen:"Seguir con sinceridad, sin doblez, trae éxito sostenido. Adaptarse a lo que el tiempo pide —y no aferrarse a lo que ya pasó— es la sabiduría de este signo.",
 imagen:"En medio del lago hay trueno: así es el seguimiento. La persona noble, al caer la noche, entra a descansar y recuperar fuerzas."},
{num:18,unicode:"䷑",hanzi:"蠱",pinyin:"Gǔ",nombre:"La Reparación de lo Corrompido",subtitulo:"",trigInf:"xun",trigSup:"gen",
 esencia:"Sanar lo que la quietud dejó decaer",
 narracion:"El viento sopla bajo la montaña inmóvil: el estancamiento ha dejado que algo se corrompa. Es el llamado a reparar con paciencia lo que la inercia fue descuidando.",
 dictamen:"Lo que se ha dejado decaer puede repararse si se actúa con determinación, revisando primero las causas antes de emprender el remedio. El trabajo hecho a tiempo trae buena fortuna.",
 imagen:"Bajo la montaña sopla el viento: así es la reparación de lo corrompido. La persona noble estimula a los demás y fortalece su propio carácter."},
{num:19,unicode:"䷒",hanzi:"臨",pinyin:"Lín",nombre:"El Acercamiento",subtitulo:"",trigInf:"dui",trigSup:"kun",
 esencia:"La influencia que crece como marea",
 narracion:"El lago se extiende bajo la vasta llanura: una fuerza gozosa que se acerca y crece, como una marea que gana terreno paso a paso sin prisa.",
 dictamen:"El acercamiento sincero trae gran fortuna mientras dure su avance; pero conviene actuar mientras el impulso favorece, porque toda marea también encuentra su momento de retroceso.",
 imagen:"Sobre el lago está la tierra: así es el acercamiento. La persona noble enseña sin agotarse y sostiene al pueblo sin límite en su tolerancia."},
{num:20,unicode:"䷓",hanzi:"觀",pinyin:"Guān",nombre:"La Contemplación",subtitulo:"",trigInf:"kun",trigSup:"xun",
 esencia:"Observar desde la altura para comprender",
 narracion:"El viento recorre la vasta llanura, tocando todo sin apegarse a nada: es la mirada elevada, la contemplación serena que observa antes de actuar.",
 dictamen:"Antes de intervenir, hay que observar con la calma de quien mira desde una torre, sin prisa por juzgar. Quien contempla su propia vida con honestidad —y no solo la ajena— gana en claridad.",
 imagen:"El viento se mueve sobre la tierra: así es la contemplación. Los antiguos reyes recorrían las regiones para observar al pueblo e instruirlo."},
{num:21,unicode:"䷔",hanzi:"噬嗑",pinyin:"Shì Kè",nombre:"Morder Atravesando",subtitulo:"",trigInf:"zhen",trigSup:"li",
 esencia:"Romper el obstáculo que impide la unión",
 narracion:"El trueno y el relámpago se combinan: fuerza que golpea y luz que revela. Es la imagen de morder con firmeza aquello que se interpone, como la mandíbula que atraviesa el obstáculo entre los labios.",
 dictamen:"Cuando algo se interpone entre las partes, es necesario actuar con decisión —aplicar la norma con firmeza pero con justicia— para restablecer la unión. Evitar el conflicto solo prolonga el obstáculo.",
 imagen:"Trueno y relámpago: así es morder atravesando. Los antiguos reyes esclarecían las leyes y hacían cumplir los castigos con claridad."},
{num:22,unicode:"䷕",hanzi:"賁",pinyin:"Bì",nombre:"La Gracia",subtitulo:"El Adorno",trigInf:"li",trigSup:"gen",
 esencia:"El adorno que revela sin ocultar la esencia",
 narracion:"El fuego arde al pie de la montaña, iluminando su superficie sin transformar su solidez: es el adorno, la gracia exterior que embellece sin cambiar lo esencial.",
 dictamen:"Los pequeños asuntos prosperan con belleza y forma cuidada, pero las decisiones grandes no deben apoyarse solo en la apariencia. El verdadero valor está debajo del adorno, no en él.",
 imagen:"Fuego al pie de la montaña: así es la gracia. La persona noble esclarece los asuntos comunes, pero nunca decide juicios importantes solo por su apariencia."},
{num:23,unicode:"䷖",hanzi:"剝",pinyin:"Bō",nombre:"El Desmoronamiento",subtitulo:"",trigInf:"kun",trigSup:"gen",
 esencia:"La estructura que se erosiona desde abajo",
 narracion:"Una montaña se asienta sobre la tierra llana, pero su base se va deshaciendo poco a poco: es el desmoronamiento lento, la erosión que avanza desde los cimientos.",
 dictamen:"No conviene actuar ni avanzar mientras dura la erosión; es momento de resguardarse y esperar. Como la montaña que finalmente vuelve a ser llanura, todo declive también se agota.",
 imagen:"La montaña se apoya sobre la tierra: así es el desmoronamiento. Quienes están arriba consolidan lo que está debajo de ellos para dar estabilidad a su morada."},
{num:24,unicode:"䷗",hanzi:"復",pinyin:"Fù",nombre:"El Retorno",subtitulo:"",trigInf:"zhen",trigSup:"kun",
 esencia:"El primer trazo de luz que regresa",
 narracion:"El trueno duerme aún bajo la vasta tierra, pero un solo trazo de fuerza ya se agita en lo profundo: es el punto de inflexión, el retorno del movimiento tras el reposo más completo.",
 dictamen:"Después del punto más bajo, el cambio regresa sin violencia. Es tiempo de descanso y reflexión antes de retomar el camino; el movimiento nuevo, aunque pequeño, trae buena fortuna si se deja madurar.",
 imagen:"El trueno está en medio de la tierra: así es el retorno. Los antiguos reyes cerraban los pasos fronterizos en el solsticio, dejando que el nuevo impulso madurase en calma."},
{num:25,unicode:"䷘",hanzi:"无妄",pinyin:"Wú Wàng",nombre:"La Inocencia",subtitulo:"Lo Inesperado",trigInf:"zhen",trigSup:"qian",
 esencia:"Actuar en sintonía con lo espontáneo",
 narracion:"El trueno se mueve bajo el cielo entero: fuerza espontánea que no calcula ni manipula. Es la inocencia genuina, la acción que surge de lo natural y no del cálculo.",
 dictamen:"Actuar sin segundas intenciones trae gran fortuna sostenida; forzar lo que no fluye con naturalidad, en cambio, trae desgracia. Lo espontáneo y sincero no necesita justificarse.",
 imagen:"Bajo el cielo se mueve el trueno: así es la inocencia. Los antiguos reyes, en sintonía con el tiempo, nutrían a todos los seres."},
{num:26,unicode:"䷙",hanzi:"大畜",pinyin:"Dà Xù",nombre:"La Fuerza Domesticadora de lo Grande",subtitulo:"",trigInf:"qian",trigSup:"gen",
 esencia:"Contener y acumular una fuerza inmensa",
 narracion:"El cielo entero queda contenido bajo la montaña: fuerza descomunal, disciplinada y guardada, que se acumula en silencio antes de manifestarse.",
 dictamen:"Detener lo excesivo con firmeza —incluso las propias ambiciones desbordadas— fortalece el carácter. La energía contenida hoy se convierte en la capacidad de emprender grandes cosas mañana.",
 imagen:"El cielo dentro de la montaña: así es la fuerza domesticadora de lo grande. La persona noble se nutre del conocimiento de muchas palabras y hechos pasados para fortalecer su virtud."},
{num:27,unicode:"䷚",hanzi:"頤",pinyin:"Yí",nombre:"Las Comisuras de la Boca",subtitulo:"El Nutrir",trigInf:"zhen",trigSup:"gen",
 esencia:"El nutrir correcto, de adentro hacia afuera",
 narracion:"El trueno se mueve en la base, la montaña se aquieta en la cima: como una boca abierta, cuya solidez está en los extremos y cuyo vacío en el medio pide ser llenado con cuidado.",
 dictamen:"Lo que se ingiere —alimento, palabras, ideas— define la salud del cuerpo y del espíritu. Observar bien qué se nutre y cómo se nutre a los demás trae buena fortuna sostenida.",
 imagen:"Bajo la montaña está el trueno: así son las comisuras de la boca. La persona noble cuida sus palabras y modera su comer y beber."},
{num:28,unicode:"䷛",hanzi:"大過",pinyin:"Dà Guò",nombre:"La Preponderancia de lo Grande",subtitulo:"",trigInf:"xun",trigSup:"dui",
 esencia:"El peso que excede su propio sostén",
 narracion:"Cuatro trazos fuertes se acumulan en el centro mientras los extremos, débiles, apenas sostienen la carga: es la viga que se comba bajo su propio peso, la tensión de lo excesivo.",
 dictamen:"La situación es extraordinaria y exige medidas extraordinarias, aunque el peso resulte incómodo. Sostenerse con firmeza, incluso en soledad, permite atravesar el momento crítico.",
 imagen:"El lago cubre los árboles: así es la preponderancia de lo grande. La persona noble, cuando está sola, permanece firme sin temor, y si debe retirarse del mundo lo hace sin tristeza."},
{num:29,unicode:"䷜",hanzi:"坎",pinyin:"Kǎn",nombre:"Lo Abismal",subtitulo:"El Agua",trigInf:"kan",trigSup:"kan",
 esencia:"El peligro repetido que enseña a fluir",
 narracion:"El agua se repite dos veces, cayendo de abismo en abismo: el peligro no se evita, se atraviesa. Como el agua misma, que nunca deja de fluir hacia su curso, aun entre rocas.",
 dictamen:"En medio del peligro repetido, la sinceridad del corazón es lo único que sostiene. No hay que temer al abismo sino aprender su ritmo, como el agua que encuentra siempre su cauce.",
 imagen:"El agua llega una y otra vez: así es lo abismal. La persona noble se mantiene fiel a su virtud constante y practica el arte de la enseñanza."},
{num:30,unicode:"䷝",hanzi:"離",pinyin:"Lí",nombre:"Lo Adherente",subtitulo:"El Fuego",trigInf:"li",trigSup:"li",
 esencia:"La claridad que se sostiene en otra cosa",
 narracion:"El fuego se repite dos veces, brillando sin cesar: pero el fuego, a diferencia del agua, no tiene forma propia; necesita adherirse a algo para arder. Es la claridad que depende de aquello que ilumina.",
 dictamen:"Como la vaca dócil que se deja guiar, la persistencia serena trae buena fortuna. La claridad interior debe apoyarse en lo correcto, no en lo brillante, para sostenerse en el tiempo.",
 imagen:"La claridad se levanta dos veces: así es lo adherente. El gran hombre, siguiendo este signo, mantiene su luz brillando en las cuatro direcciones."},
{num:31,unicode:"䷞",hanzi:"咸",pinyin:"Xián",nombre:"El Influjo",subtitulo:"",trigInf:"gen",trigSup:"dui",
 esencia:"La atracción mutua sin palabras",
 narracion:"La montaña recibe al lago, el lago desciende hacia la montaña: dos fuerzas que se atraen sin forzarse, la resonancia espontánea entre lo quieto y lo gozoso.",
 dictamen:"Este es un signo de cortejo y de encuentro genuino: la atracción sincera trae buena fortuna cuando nace de la humildad, no de la insistencia. Recibir al otro con el corazón abierto abre camino al vínculo verdadero.",
 imagen:"Sobre la montaña hay un lago: así es el influjo. La persona noble mantiene su mente abierta y receptiva, dispuesta a acoger a los demás."},
{num:32,unicode:"䷟",hanzi:"恆",pinyin:"Héng",nombre:"La Duración",subtitulo:"",trigInf:"xun",trigSup:"zhen",
 esencia:"Lo constante que se sostiene en el movimiento",
 narracion:"El trueno resuena mientras el viento sopla: dos fuerzas en movimiento constante, que no se agotan porque no se detienen. Es la duración que nace del cambio bien ordenado, no de la inmovilidad.",
 dictamen:"Perseverar en el propio camino, sin desviarse por impulso ni aferrarse por miedo, trae éxito sin reproche. La verdadera duración no es quietud: es ritmo sostenido.",
 imagen:"Trueno y viento: así es la duración. La persona noble se mantiene firme y no cambia de rumbo."},
{num:33,unicode:"䷠",hanzi:"遯",pinyin:"Dùn",nombre:"El Retiro",subtitulo:"",trigInf:"gen",trigSup:"qian",
 esencia:"Retirarse con dignidad, a tiempo",
 narracion:"El cielo se aleja hacia arriba mientras la montaña, abajo, ve crecer lo pequeño a su alrededor: es el momento de retirarse con calma, antes de que el declive obligue a huir con premura.",
 dictamen:"El retiro oportuno, hecho con serenidad y sin resentimiento, trae éxito en lo pequeño. Alejarse a tiempo de lo que decae protege la propia integridad para un mejor momento futuro.",
 imagen:"Bajo el cielo hay una montaña: así es el retiro. La persona noble se mantiene distante de lo inferior, no con odio, sino con reserva digna."},
{num:34,unicode:"䷡",hanzi:"大壯",pinyin:"Dà Zhuàng",nombre:"El Poder de lo Grande",subtitulo:"",trigInf:"qian",trigSup:"zhen",
 esencia:"La fuerza en su máximo despliegue",
 narracion:"El trueno resuena en lo alto del cielo: un poder inmenso en plena marcha. Es la fuerza que ya no puede contenerse, la energía en su punto de mayor despliegue.",
 dictamen:"El gran poder trae éxito solo si se ejerce con rectitud; usado sin mesura, se vuelve contra quien lo posee, como el carnero que se enreda los cuernos al embestir la cerca.",
 imagen:"El trueno está en lo alto del cielo: así es el poder de lo grande. La persona noble no da un paso que no esté conforme al orden establecido."},
{num:35,unicode:"䷢",hanzi:"晉",pinyin:"Jìn",nombre:"El Progreso",subtitulo:"",trigInf:"kun",trigSup:"li",
 esencia:"El avance luminoso y sostenido",
 narracion:"El sol se eleva sobre la vasta tierra, iluminando cada vez más terreno: es el progreso constante, el avance que gana espacio con la sola fuerza de brillar.",
 dictamen:"El progreso llega con generosidad, casi sin esfuerzo, como el sol que asciende cada mañana. Recibir con gratitud lo que llega, sin apresurar el paso, sostiene la buena fortuna.",
 imagen:"La claridad se alza sobre la tierra: así es el progreso. La persona noble hace brillar por sí misma su virtud luminosa."},
{num:36,unicode:"䷣",hanzi:"明夷",pinyin:"Míng Yí",nombre:"El Oscurecimiento de la Luz",subtitulo:"",trigInf:"li",trigSup:"kun",
 esencia:"La claridad herida que debe protegerse",
 narracion:"El sol se hunde bajo la tierra: la luz que antes brillaba ahora queda oculta, herida por la oscuridad que la rodea. Es tiempo de resguardar la propia claridad en silencio.",
 dictamen:"En tiempos donde la verdad se calla y el poder daña a quien brilla demasiado, conviene velar la propia luz y perseverar en la dificultad sin exponerse sin necesidad.",
 imagen:"La claridad ha entrado en la tierra: así es el oscurecimiento de la luz. La persona noble, ante las masas, oculta su brillo y aun así permanece luminosa por dentro."},
{num:37,unicode:"䷤",hanzi:"家人",pinyin:"Jiā Rén",nombre:"La Familia",subtitulo:"",trigInf:"li",trigSup:"xun",
 esencia:"El orden cálido que sostiene el hogar",
 narracion:"El fuego arde en el hogar y el viento lleva su calor por toda la casa: es la familia, el orden íntimo donde cada quien encuentra su lugar y su tarea.",
 dictamen:"La firmeza de quien cuida el hogar —con roles claros y afecto genuino— trae fortuna duradera. El orden dentro de la casa se refleja después en el orden del mundo entero.",
 imagen:"El viento sale del fuego: así es la familia. La persona noble tiene sustancia en sus palabras y constancia en su conducta."},
{num:38,unicode:"䷥",hanzi:"睽",pinyin:"Kuí",nombre:"La Oposición",subtitulo:"",trigInf:"dui",trigSup:"li",
 esencia:"Las diferencias que aún pueden dialogar",
 narracion:"El fuego sube, el lago desciende: dos naturalezas que se alejan, pero no se destruyen. Es la oposición que, bien mirada, todavía guarda un punto de encuentro posible.",
 dictamen:"En medio del desacuerdo, los pequeños asuntos aún pueden resolverse bien. No conviene forzar la unión completa; basta con encontrar puntos de contacto y avanzar con paciencia en lo que sí es posible.",
 imagen:"Arriba el fuego, abajo el lago: así es la oposición. La persona noble, en medio de lo que la asemeja a otros, sabe distinguir lo que la hace diferente."},
{num:39,unicode:"䷦",hanzi:"蹇",pinyin:"Jiǎn",nombre:"El Obstáculo",subtitulo:"",trigInf:"gen",trigSup:"kan",
 esencia:"El paso difícil que exige aliados",
 narracion:"El agua peligrosa se extiende sobre la montaña inmóvil: el camino está cortado, difícil de transitar en soledad. Es el obstáculo que pide detenerse a pensar antes de avanzar.",
 dictamen:"Avanzar en soledad frente al obstáculo trae dificultad; buscar ayuda y consejo de quien tiene experiencia trae buena fortuna. A veces retroceder un paso es la única forma de encontrar un mejor camino.",
 imagen:"Sobre la montaña hay agua: así es el obstáculo. La persona noble se examina a sí misma y cultiva su virtud frente a la dificultad."},
{num:40,unicode:"䷧",hanzi:"解",pinyin:"Xiè",nombre:"La Liberación",subtitulo:"",trigInf:"kan",trigSup:"zhen",
 esencia:"La tensión que finalmente se disuelve",
 narracion:"El trueno resuena y la lluvia cae, liberando la tensión acumulada en el aire: es el alivio después del peligro, el nudo que finalmente se deshace.",
 dictamen:"Cuando la dificultad empieza a soltarse, conviene actuar pronto para consolidar lo ganado y no demorar el regreso a la normalidad. Perdonar los errores pasados abre camino a la nueva etapa.",
 imagen:"Trueno y lluvia se alzan juntos: así es la liberación. La persona noble perdona las faltas y es indulgente con los errores ajenos."},
{num:41,unicode:"䷨",hanzi:"損",pinyin:"Sǔn",nombre:"La Disminución",subtitulo:"",trigInf:"dui",trigSup:"gen",
 esencia:"Restar abajo para fortalecer arriba",
 narracion:"El lago se hunde al pie de la montaña, cediendo su humedad para que la montaña crezca más fértil: es la disminución consciente, el sacrificio de lo propio en beneficio de un bien mayor.",
 dictamen:"Disminuir lo excesivo de uno mismo —el enojo, el deseo, el exceso— fortalece el espíritu. Lo que hoy se resta con sinceridad se transforma después en verdadera ganancia.",
 imagen:"Al pie de la montaña hay un lago: así es la disminución. La persona noble contiene su ira y frena sus deseos."},
{num:42,unicode:"䷩",hanzi:"益",pinyin:"Yì",nombre:"El Aumento",subtitulo:"",trigInf:"zhen",trigSup:"xun",
 esencia:"Lo que fluye desde arriba hacia abajo",
 narracion:"El viento y el trueno se refuerzan mutuamente: lo alto cede en beneficio de lo bajo, y así ambos crecen juntos. Es el aumento que nace de compartir, no de acumular.",
 dictamen:"Es tiempo favorable para emprender y para cruzar las grandes aguas. Quien reparte generosamente desde una posición de ventaja ve crecer su propia fortuna junto con la de los demás.",
 imagen:"Viento y trueno: así es el aumento. La persona noble, al ver el bien, lo imita; al reconocer su propia falta, la corrige."},
{num:43,unicode:"䷪",hanzi:"夬",pinyin:"Guài",nombre:"La Resolución",subtitulo:"",trigInf:"qian",trigSup:"dui",
 esencia:"El último obstáculo antes de la victoria total",
 narracion:"El lago se ha elevado hasta lo más alto del cielo, a punto de desbordarse: cinco trazos fuertes empujan un único trazo débil que resiste en la cima. Es la resolución decidida frente al último resquicio de duda.",
 dictamen:"Hay que proclamar la verdad con claridad, incluso ante la propia gente, pero sin recurrir a la violencia. Anunciar el peligro con antelación y actuar con firmeza asegura el resultado.",
 imagen:"El lago ha subido al cielo: así es la resolución. La persona noble reparte sus bienes entre quienes la rodean y evita acumular virtud solo para sí."},
{num:44,unicode:"䷫",hanzi:"姤",pinyin:"Gòu",nombre:"El Encuentro",subtitulo:"",trigInf:"xun",trigSup:"qian",
 esencia:"Lo inesperado que se presenta sin ser llamado",
 narracion:"Un único trazo suave se desliza bajo cinco trazos fuertes: algo se presenta de improviso, sin haber sido convocado. Es el encuentro inesperado, que puede ser fértil o peligroso según cómo se lo reciba.",
 dictamen:"Lo que llega sin anuncio merece cautela: no todo encuentro conviene profundizarlo por igual. Observar antes de comprometerse evita que lo pequeño e inofensivo crezca hasta volverse invasivo.",
 imagen:"Bajo el cielo sopla el viento: así es el encuentro. Los gobernantes, siguiendo este signo, difunden sus disposiciones en las cuatro direcciones."},
{num:45,unicode:"䷬",hanzi:"萃",pinyin:"Cuì",nombre:"La Reunión",subtitulo:"",trigInf:"kun",trigSup:"dui",
 esencia:"Las masas que convergen en torno a un centro",
 narracion:"El lago se junta sobre la tierra llana, acumulando sus aguas: es la reunión de las masas alrededor de un propósito o de quien sabe convocarlas.",
 dictamen:"Reunir a otros exige un centro claro y gestos sinceros que sostengan la confianza del grupo. Prepararse ante lo inesperado protege la unión ya lograda.",
 imagen:"El lago está sobre la tierra: así es la reunión. La persona noble repara sus herramientas para prevenir sucesos imprevistos."},
{num:46,unicode:"䷭",hanzi:"升",pinyin:"Shēng",nombre:"El Empuje Ascendente",subtitulo:"",trigInf:"xun",trigSup:"kun",
 esencia:"El crecimiento silencioso hacia la luz",
 narracion:"Bajo la tierra crece un brote de madera, empujando hacia arriba sin prisa ni ruido: es el ascenso natural, el crecimiento que no se fuerza sino que se cultiva paso a paso.",
 dictamen:"El avance gradual y constante, sin atajos, trae gran fortuna. Consultar a quien tiene experiencia y dirigirse hacia la luz favorece este momento de crecimiento sostenido.",
 imagen:"En medio de la tierra crece la madera: así es el empuje ascendente. La persona noble se adapta con docilidad y acumula pequeños esfuerzos hasta alcanzar lo alto."},
{num:47,unicode:"䷮",hanzi:"困",pinyin:"Kùn",nombre:"El Agotamiento",subtitulo:"",trigInf:"kan",trigSup:"dui",
 esencia:"El lago que se ha secado sobre sí mismo",
 narracion:"El agua se ha retirado por debajo del lago, dejándolo vacío y agotado: es la opresión que viene de recursos escasos, la fuerza atrapada sin salida visible.",
 dictamen:"En medio de la escasez, hablar demasiado no encuentra crédito; conviene actuar con palabras breves y sinceras, y sostener la propia alegría interior aun en la adversidad.",
 imagen:"El lago está sin agua: así es el agotamiento. La persona noble arriesga su vida por cumplir su propósito más profundo."},
{num:48,unicode:"䷯",hanzi:"井",pinyin:"Jǐng",nombre:"El Pozo",subtitulo:"",trigInf:"xun",trigSup:"kan",
 esencia:"La fuente que no cambia aunque todo cambie",
 narracion:"El agua sube desde la madera hundida en la tierra: es el pozo, la fuente inagotable que permanece en su lugar mientras las ciudades a su alrededor se construyen y se derrumban.",
 dictamen:"Como el pozo que nutre a todos por igual, lo que verdaderamente sostiene a una comunidad no cambia con las modas. Cuidar la fuente propia es más importante que mudarse constantemente de lugar.",
 imagen:"Sobre la madera hay agua: así es el pozo. La persona noble anima al pueblo al trabajo mutuo y lo exhorta a ayudarse entre sí."},
{num:49,unicode:"䷰",hanzi:"革",pinyin:"Gé",nombre:"La Revolución",subtitulo:"",trigInf:"li",trigSup:"dui",
 esencia:"El cambio de piel cuando el tiempo lo exige",
 narracion:"El fuego arde bajo el lago, y el lago apaga al fuego: dos naturalezas que no pueden coexistir sin transformarse. Es la revolución, el cambio de piel que llega cuando lo viejo ya no puede sostenerse.",
 dictamen:"El cambio verdadero solo convence cuando ya es evidente para todos, y solo debe emprenderse con la confianza genuina de quienes lo viven. Un cambio prematuro o impuesto trae más daño que beneficio.",
 imagen:"En el lago hay fuego: así es la revolución. La persona noble ordena el calendario y esclarece las estaciones del tiempo."},
{num:50,unicode:"䷱",hanzi:"鼎",pinyin:"Dǐng",nombre:"El Caldero",subtitulo:"",trigInf:"xun",trigSup:"li",
 esencia:"El recipiente que transforma para nutrir",
 narracion:"La madera alimenta el fuego bajo el caldero: es el recipiente sagrado que transforma lo crudo en alimento, lo material en sustento comunitario.",
 dictamen:"Este es un signo de gran fortuna: transformar los recursos disponibles para nutrir a los demás, con firmeza y claridad, atrae éxito sostenido y reconocimiento merecido.",
 imagen:"Sobre la madera hay fuego: así es el caldero. La persona noble consolida su destino manteniendo recta su posición."},
{num:51,unicode:"䷲",hanzi:"震",pinyin:"Zhèn",nombre:"Lo Suscitativo",subtitulo:"El Trueno",trigInf:"zhen",trigSup:"zhen",
 esencia:"El sobresalto que despierta y purifica",
 narracion:"El trueno se repite dos veces, sacudiendo todo a su paso: el sobresalto inicial asusta, pero después deja una claridad renovada, como el aire limpio tras la tormenta.",
 dictamen:"El shock inicial trae temor, pero quien mantiene la calma en medio del estruendo —sin dejar caer lo que sostiene en sus manos— sale fortalecido. El miedo bien atravesado enseña más que la comodidad.",
 imagen:"Trueno sobre trueno: así es lo suscitativo. La persona noble, llena de temor reverente, examina su interior y corrige su conducta."},
{num:52,unicode:"䷳",hanzi:"艮",pinyin:"Gèn",nombre:"La Quietud",subtitulo:"La Montaña",trigInf:"gen",trigSup:"gen",
 esencia:"La inmovilidad que no es indiferencia",
 narracion:"La montaña se repite dos veces, inmóvil sobre sí misma: no es ausencia de vida, es la quietud consciente, el detenerse justo donde corresponde detenerse.",
 dictamen:"Detener el movimiento en el momento justo, sin forzar ni la acción ni la inacción, trae paz sin reproche. Aquietar la mente —soltar el apego, no reprimirlo— es la verdadera práctica de este signo.",
 imagen:"Montañas unidas: así es la quietud. La persona noble no deja que sus pensamientos vayan más allá de su propia situación presente."},
{num:53,unicode:"䷴",hanzi:"漸",pinyin:"Jiàn",nombre:"El Desarrollo Gradual",subtitulo:"",trigInf:"gen",trigSup:"xun",
 esencia:"El paso a paso que no se salta etapas",
 narracion:"El viento sopla suavemente sobre la montaña, y un árbol crece lento pero firme en su ladera: es el desarrollo gradual, el progreso que respeta cada etapa antes de pasar a la siguiente.",
 dictamen:"Como el ave que anida paso a paso, el avance ordenado y paciente asegura un final favorable. Saltarse etapas por ansiedad rompe lo que se estaba construyendo.",
 imagen:"Sobre la montaña hay un árbol: así es el desarrollo gradual. La persona noble permanece en su virtud digna y así mejora las costumbres."},
{num:54,unicode:"䷵",hanzi:"歸妹",pinyin:"Guī Mèi",nombre:"La Doncella que se Casa",subtitulo:"",trigInf:"dui",trigSup:"zhen",
 esencia:"Entrar a una situación en posición desigual",
 narracion:"El trueno agita al lago desde arriba: una fuerza mayor pone en movimiento a otra menor, como quien entra a una nueva etapa sin ocupar el lugar principal.",
 dictamen:"Actuar por impulso o ambición en una posición subordinada trae desventura; solo la sinceridad y la paciencia, sin forzar un lugar que no corresponde todavía, permiten que la situación madure bien.",
 imagen:"Trueno sobre el lago: así es la doncella que se casa. La persona noble comprende lo transitorio de las cosas y reconoce las consecuencias que aún están por venir."},
{num:55,unicode:"䷶",hanzi:"豐",pinyin:"Fēng",nombre:"La Abundancia",subtitulo:"",trigInf:"li",trigSup:"zhen",
 esencia:"El punto más alto de plenitud",
 narracion:"El trueno y el relámpago se combinan en su máxima expresión: es el mediodía de la existencia, el momento de mayor abundancia y claridad, que por su misma plenitud ya empieza a inclinarse hacia el declive.",
 dictamen:"Como el sol al mediodía, la abundancia no debe generar tristeza por su carácter pasajero, sino alegría por vivirla plenamente mientras dura. Actuar con decisión en este pico de fortuna es propio de quien sabe conducir.",
 imagen:"Trueno y relámpago llegan juntos: así es la abundancia. La persona noble decide los litigios y ejecuta los castigos con la misma claridad del relámpago."},
{num:56,unicode:"䷷",hanzi:"旅",pinyin:"Lǚ",nombre:"El Andariego",subtitulo:"",trigInf:"gen",trigSup:"li",
 esencia:"Quien avanza sin raíces fijas",
 narracion:"El fuego arde sobre la montaña inmóvil, avanzando de cumbre en cumbre sin quedarse en ninguna: es el andariego, quien atraviesa lugares ajenos sin poder echar raíces.",
 dictamen:"En tierra ajena, la prudencia y la modestia son más valiosas que la audacia. Mantener la rectitud sin buscar protagonismo asegura pequeños éxitos incluso lejos de casa.",
 imagen:"Fuego sobre la montaña: así es el andariego. La persona noble es clara y cautelosa al aplicar castigos, y no prolonga los litigios."},
{num:57,unicode:"䷸",hanzi:"巽",pinyin:"Xùn",nombre:"Lo Suave",subtitulo:"El Viento",trigInf:"xun",trigSup:"xun",
 esencia:"La penetración gentil y persistente",
 narracion:"El viento se repite dos veces, entrando por cada rendija sin golpear nunca de frente: es la fuerza suave que penetra donde lo rígido no puede, con constancia más que con violencia.",
 dictamen:"Los pequeños logros llegan a través de la insistencia gentil, no de la imposición. Consultar a quien tiene autoridad, y repetir el intento con paciencia cuando algo no sale a la primera, trae éxito sostenido.",
 imagen:"Vientos que se sostienen uno tras otro: así es lo suave. La persona noble difunde sus disposiciones y así lleva a cabo sus asuntos."},
{num:58,unicode:"䷹",hanzi:"兌",pinyin:"Duì",nombre:"Lo Gozoso",subtitulo:"El Lago",trigInf:"dui",trigSup:"dui",
 esencia:"La alegría compartida entre iguales",
 narracion:"El lago se repite dos veces, reflejándose a sí mismo: es la alegría que se multiplica al compartirse, el gozo genuino que nace del encuentro entre iguales.",
 dictamen:"La alegría sincera, cultivada con firmeza interior y no con complacencia vacía, trae éxito. Compartir el entusiasmo con quienes también aportan sinceridad multiplica la buena fortuna de todos.",
 imagen:"Lagos unidos uno junto a otro: así es lo gozoso. La persona noble se reúne con sus amigos para conversar y estudiar juntos."},
{num:59,unicode:"䷺",hanzi:"渙",pinyin:"Huàn",nombre:"La Disolución",subtitulo:"",trigInf:"kan",trigSup:"xun",
 esencia:"El hielo que el viento cálido derrite",
 narracion:"El viento sopla sobre el agua y la dispersa en gotas finas: es la disolución de lo que estaba rígido o dividido, el deshielo de tensiones que ya no servían a nadie.",
 dictamen:"Disolver el egoísmo y las divisiones internas —a través de gestos compartidos de unión— trae buena fortuna. Es momento de cruzar las grandes aguas y reunir lo que estaba disperso.",
 imagen:"El viento se mueve sobre el agua: así es la disolución. Los antiguos reyes erigían templos para reunir al pueblo disperso."},
{num:60,unicode:"䷻",hanzi:"節",pinyin:"Jié",nombre:"La Limitación",subtitulo:"",trigInf:"dui",trigSup:"kan",
 esencia:"El límite que da forma y sentido",
 narracion:"El agua se acumula sobre el lago, contenida por sus propias orillas: sin ese límite se desbordaría y perdería su forma. Es la limitación sana, la que ordena en vez de aprisionar.",
 dictamen:"Poner límites claros trae éxito, pero límites demasiado duros traen amargura y no deben sostenerse por mucho tiempo. La medida justa es la que se puede cumplir con alegría.",
 imagen:"Sobre el lago hay agua: así es la limitación. La persona noble crea números y medidas, y examina la virtud y la conducta correctas."},
{num:61,unicode:"䷼",hanzi:"中孚",pinyin:"Zhōng Fú",nombre:"La Verdad Interior",subtitulo:"",trigInf:"dui",trigSup:"xun",
 esencia:"La sinceridad que atraviesa cualquier distancia",
 narracion:"El viento sopla sobre el lago, y el lago responde moviéndose en armonía: es la verdad interior, la sinceridad tan genuina que llega hasta los seres más alejados, incluso a los que parecen indiferentes.",
 dictamen:"La sinceridad profunda conmueve incluso a quienes no comparten los mismos vínculos: puede atravesar los momentos más difíciles, siempre que el corazón esté libre de doblez.",
 imagen:"Sobre el lago sopla el viento: así es la verdad interior. La persona noble delibera con cuidado sobre los casos difíciles y suspende las condenas cuando hay duda genuina."},
{num:62,unicode:"䷽",hanzi:"小過",pinyin:"Xiǎo Guò",nombre:"La Preponderancia de lo Pequeño",subtitulo:"",trigInf:"gen",trigSup:"zhen",
 esencia:"Los gestos pequeños en tiempos excepcionales",
 narracion:"El trueno resuena sobre la montaña inmóvil, con un sonido que se extiende más allá de lo esperado para su tamaño: son los pequeños actos que, en momentos excepcionales, pesan más de lo habitual.",
 dictamen:"No conviene apuntar a las grandes hazañas en este momento, sino cuidar los detalles pequeños con esmero: como el ave que vuela bajo en vez de remontar demasiado alto, la humildad en la acción trae buena fortuna.",
 imagen:"El trueno está sobre la montaña: así es la preponderancia de lo pequeño. La persona noble se inclina un poco hacia el respeto en su conducta, hacia el dolor en el duelo y hacia el ahorro en el gasto."},
{num:63,unicode:"䷾",hanzi:"既濟",pinyin:"Jì Jì",nombre:"Después de la Consumación",subtitulo:"",trigInf:"li",trigSup:"kan",
 esencia:"Cada cosa en su lugar exacto",
 narracion:"El fuego y el agua se equilibran justo en su punto correcto, línea tras línea: es la obra ya terminada, el orden alcanzado que, precisamente por estar completo, empieza ya a pedir cuidado para no deshacerse.",
 dictamen:"El éxito ya logrado exige tanta atención como el que aún se busca: lo pequeño favorece, lo grande puede desordenarse otra vez si se descuida la vigilancia. El final es, en realidad, un nuevo comienzo disfrazado.",
 imagen:"El agua está sobre el fuego: así es después de la consumación. La persona noble medita sobre el peligro futuro y se previene contra él con antelación."},
{num:64,unicode:"䷿",hanzi:"未濟",pinyin:"Wèi Jì",nombre:"Antes de la Consumación",subtitulo:"",trigInf:"kan",trigSup:"li",
 esencia:"El último tramo, aún incierto",
 narracion:"El fuego y el agua se buscan sin terminar de encontrarse, cada línea fuera de su lugar habitual: es el umbral final, cuando casi todo está listo pero el último paso todavía puede fallar.",
 dictamen:"Como el zorro que moja su cola justo al cruzar el río casi entero, el descuido en el tramo final puede arruinar lo avanzado. Proceder con el mismo cuidado del inicio, hasta el último paso, asegura que el cambio se complete bien.",
 imagen:"El fuego está sobre el agua: así es antes de la consumación. La persona noble es cuidadosa al distinguir las cosas y las coloca cada una en su lugar correcto."},
];

// Completa el campo `binario` de cada hexagrama a partir de sus trigramas
// (trigrama inferior = líneas 1-3, trigrama superior = líneas 4-6, de abajo hacia arriba).
HEXAGRAMAS.forEach(h => {
  h.binario = TRIGRAMAS[h.trigInf].binario + TRIGRAMAS[h.trigSup].binario;
});

/* ------------------------ helpers ------------------------ */
function unicodeFor(num){ return String.fromCodePoint(0x4DC0 + (num - 1)); }
function findHexagramByBinario(bin){ return HEXAGRAMAS.find(h => h.binario === bin); }
function nombreTrigrama(clave){
  const t = TRIGRAMAS[clave];
  return `${t.simbolo} ${t.hanzi} (${t.pinyin}) — ${t.nombre}`;
}
