# -*- coding: utf-8 -*-
"""
Dataset de obras de dominio público para "Obra del Día".
Las imágenes se sirven desde Wikimedia Commons vía Special:FilePath,
que redirige siempre al archivo original sin depender de hashes de carpeta.
"""

PAINTINGS = [
    {
        "id": "mona-lisa",
        "title": "La Mona Lisa",
        "artist": "Leonardo da Vinci",
        "year": "c. 1503–1517",
        "museum": "Museo del Louvre, París",
        "file": "Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
        "aliases": ["mona lisa", "la gioconda", "gioconda", "monna lisa"],
        "artist_aliases": ["leonardo", "da vinci", "leonardo da vinci"],
        "fun_fact": "Fue robada del Louvre en 1911 por un empleado del museo, lo que la catapultó a la fama mundial.",
    },
    {
        "id": "starry-night",
        "title": "La Noche Estrellada",
        "artist": "Vincent van Gogh",
        "year": "1889",
        "museum": "MoMA, Nueva York",
        "file": "Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
        "aliases": ["la noche estrellada", "noche estrellada", "starry night"],
        "artist_aliases": ["van gogh", "vincent van gogh", "vincent"],
        "fun_fact": "Van Gogh la pintó desde la ventana de su cuarto en un sanatorio psiquiátrico en Saint-Rémy-de-Provence.",
    },
    {
        "id": "the-scream",
        "title": "El Grito",
        "artist": "Edvard Munch",
        "year": "1893",
        "museum": "Galería Nacional de Noruega, Oslo",
        "file": "Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg",
        "aliases": ["el grito", "the scream", "grito"],
        "artist_aliases": ["munch", "edvard munch"],
        "fun_fact": "Munch dijo haberla pintado tras sentir 'un grito infinito atravesando la naturaleza' durante un atardecer.",
    },
    {
        "id": "pearl-earring",
        "title": "La Joven de la Perla",
        "artist": "Johannes Vermeer",
        "year": "c. 1665",
        "museum": "Mauritshuis, La Haya",
        "file": "1665_Girl_with_a_Pearl_Earring.jpg",
        "aliases": ["la joven de la perla", "joven de la perla", "girl with a pearl earring", "la chica de la perla"],
        "artist_aliases": ["vermeer", "johannes vermeer"],
        "fun_fact": "No es un retrato real sino un 'tronie', un estudio de expresión y vestuario típico del barroco holandés.",
    },
    {
        "id": "great-wave",
        "title": "La Gran Ola de Kanagawa",
        "artist": "Katsushika Hokusai",
        "year": "c. 1831",
        "museum": "Varios museos (grabado en xilografía)",
        "file": "The_Great_Wave_off_Kanagawa.jpg",
        "aliases": ["la gran ola", "la gran ola de kanagawa", "great wave", "the great wave"],
        "artist_aliases": ["hokusai", "katsushika hokusai"],
        "fun_fact": "Es un grabado en madera, no una pintura única: se imprimieron miles de copias en su época.",
    },
    {
        "id": "american-gothic",
        "title": "Gótico Americano",
        "artist": "Grant Wood",
        "year": "1930",
        "museum": "Art Institute of Chicago",
        "file": "Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg",
        "aliases": ["gotico americano", "gótico americano", "american gothic"],
        "artist_aliases": ["grant wood"],
        "fun_fact": "Los modelos fueron la hermana del pintor y su dentista, no una pareja de granjeros real.",
    },
    {
        "id": "impression-sunrise",
        "title": "Impresión, Sol Naciente",
        "artist": "Claude Monet",
        "year": "1872",
        "museum": "Museo Marmottan Monet, París",
        "file": "Monet_-_Impression,_Sunrise.jpg",
        "aliases": ["impresion sol naciente", "impresión, sol naciente", "impression sunrise", "impresion, sol naciente"],
        "artist_aliases": ["monet", "claude monet"],
        "fun_fact": "Le dio su nombre a todo un movimiento artístico: el Impresionismo, usado al principio como burla por la crítica.",
    },
    {
        "id": "birth-of-venus",
        "title": "El Nacimiento de Venus",
        "artist": "Sandro Botticelli",
        "year": "c. 1485",
        "museum": "Galería Uffizi, Florencia",
        "file": "Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
        "aliases": ["el nacimiento de venus", "nacimiento de venus", "birth of venus"],
        "artist_aliases": ["botticelli", "sandro botticelli"],
        "fun_fact": "Está pintada sobre tela en vez de madera, algo inusual para un cuadro de esa escala en el siglo XV.",
    },
    {
        "id": "las-meninas",
        "title": "Las Meninas",
        "artist": "Diego Velázquez",
        "year": "1656",
        "museum": "Museo del Prado, Madrid",
        "file": "Las_Meninas,_by_Diego_Velázquez,_from_Prado_in_Google_Earth.jpg",
        "aliases": ["las meninas"],
        "artist_aliases": ["velazquez", "velázquez", "diego velazquez"],
        "fun_fact": "El propio Velázquez se autorretrató en la escena, pincel en mano, mirando hacia el espectador.",
    },
    {
        "id": "night-watch",
        "title": "La Ronda de Noche",
        "artist": "Rembrandt van Rijn",
        "year": "1642",
        "museum": "Rijksmuseum, Ámsterdam",
        "file": "The_Night_Watch_-_HD.jpg",
        "aliases": ["la ronda de noche", "ronda de noche", "the night watch", "ronda nocturna"],
        "artist_aliases": ["rembrandt"],
        "fun_fact": "Pese al nombre, no transcurre de noche: siglos de barniz oscurecido le dieron esa apariencia hasta su restauración.",
    },
    {
        "id": "the-kiss",
        "title": "El Beso",
        "artist": "Gustav Klimt",
        "year": "1908",
        "museum": "Belvedere, Viena",
        "file": "Gustav_Klimt_016.jpg",
        "aliases": ["el beso", "the kiss"],
        "artist_aliases": ["klimt", "gustav klimt"],
        "fun_fact": "Usó pan de oro real, una técnica heredada del trabajo de orfebre de su padre.",
    },
    {
        "id": "whistlers-mother",
        "title": "Retrato de la Madre del Artista",
        "artist": "James McNeill Whistler",
        "year": "1871",
        "museum": "Museo de Orsay, París",
        "file": "Whistlers_Mother_high_res.jpg",
        "aliases": ["la madre de whistler", "retrato de la madre del artista", "whistler's mother", "whistlers mother"],
        "artist_aliases": ["whistler", "james mcneill whistler"],
        "fun_fact": "Su título original era simplemente 'Arreglo en gris y negro No. 1'; Whistler la pensaba como un estudio de composición, no un homenaje familiar.",
    },
    {
        "id": "liberty-leading",
        "title": "La Libertad Guiando al Pueblo",
        "artist": "Eugène Delacroix",
        "year": "1830",
        "museum": "Museo del Louvre, París",
        "file": "Eugène_Delacroix_-_La_liberté_guidant_le_peuple.jpg",
        "aliases": ["la libertad guiando al pueblo", "libertad guiando al pueblo", "liberty leading the people"],
        "artist_aliases": ["delacroix", "eugene delacroix", "eugène delacroix"],
        "fun_fact": "Conmemora la Revolución de Julio de 1830 en Francia, no la Revolución Francesa de 1789 como muchos creen.",
    },
    {
        "id": "garden-earthly-delights",
        "title": "El Jardín de las Delicias",
        "artist": "El Bosco",
        "year": "c. 1500",
        "museum": "Museo del Prado, Madrid",
        "file": "The_Garden_of_earthly_delights.jpg",
        "aliases": ["el jardin de las delicias", "jardin de las delicias", "garden of earthly delights"],
        "artist_aliases": ["el bosco", "hieronymus bosch", "bosco", "bosch"],
        "fun_fact": "Es un tríptico: al cerrar sus puertas, se revela otra pintura completa del mundo antes de la creación de Eva.",
    },
    {
        "id": "wanderer-fog",
        "title": "El Caminante sobre el Mar de Nubes",
        "artist": "Caspar David Friedrich",
        "year": "c. 1818",
        "museum": "Kunsthalle de Hamburgo",
        "file": "Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog.jpeg",
        "aliases": ["el caminante sobre el mar de nubes", "caminante sobre el mar de nubes", "wanderer above the sea of fog"],
        "artist_aliases": ["caspar david friedrich", "friedrich"],
        "fun_fact": "Se convirtió en el ícono visual del Romanticismo alemán y hoy es una de las imágenes más memeadas de la historia del arte.",
    },
    {
        "id": "third-of-may",
        "title": "El Tres de Mayo de 1808",
        "artist": "Francisco de Goya",
        "year": "1814",
        "museum": "Museo del Prado, Madrid",
        "file": "El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_in_Google_Earth.jpg",
        "aliases": ["el tres de mayo", "tres de mayo", "el tres de mayo de 1808", "third of may"],
        "artist_aliases": ["goya", "francisco de goya"],
        "fun_fact": "Está considerada una de las primeras grandes obras que retrata la guerra moderna sin idealizar a los vencedores.",
    },
    {
        "id": "composition-viii",
        "title": "Composición VIII",
        "artist": "Vasili Kandinsky",
        "year": "1923",
        "museum": "Museo Guggenheim, Nueva York",
        "file": "Vassily_Kandinsky,_1923_-_Composition_8,_Guggenheim_Museum.jpg",
        "aliases": ["composicion viii", "composición viii", "composition 8", "composition viii"],
        "artist_aliases": ["kandinsky", "vasili kandinsky", "wassily kandinsky"],
        "fun_fact": "Kandinsky sostenía que ciertos colores y formas producían sonidos: una condición llamada sinestesia.",
    },
    {
        "id": "grande-jatte",
        "title": "Una Tarde de Domingo en la Isla de la Grande Jatte",
        "artist": "Georges Seurat",
        "year": "1884–1886",
        "museum": "Art Institute of Chicago",
        "file": "A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg",
        "aliases": ["la grande jatte", "domingo en la grande jatte", "una tarde de domingo en la isla de la grande jatte", "grande jatte"],
        "artist_aliases": ["seurat", "georges seurat"],
        "fun_fact": "Está pintada con puntillismo: miles de puntitos de color puro que el ojo mezcla a distancia.",
    },
]


def commons_url(filename: str, width: int = 1200) -> str:
    """URL estable de Wikimedia Commons que no depende del hash de carpeta."""
    from urllib.parse import quote

    encoded = quote(filename)
    return f"https://commons.wikimedia.org/wiki/Special:FilePath/{encoded}?width={width}"
